server {
    listen 8080;
    server_name www.hingaai.tech;

    return 301 https://hingaai.tech$request_uri;
}

server {
    listen 8080 default_server;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location = /health {
        access_log off;
        add_header Content-Type text/plain;
        return 200 'ok';
    }
}
